main: com.github.enderrun.EnderRun
version: ${version}
name: EnderRun

commands:
  endergen:
    description: Generates a new EnderGen world
    aliases: [genender]
    permission: Endergen.Generate
    usage: /[command]
  joinender:
    description: Join the Ender Run Game
    aliases: [joinenderrun]
    permission: Endergen.Join
    usage: /[command]
