main: com.github.enderrun.EnderRun
version: ${version}
name: EnderRun

commands:
  enderrun:
    description: Generates a new EnderGen world
    aliases: [genender]
    permission: Endergen.Generate
    usage: /[command]
